/**
 * Example usage of QuestionsExplorer component
 *
 * This file demonstrates how to use the QuestionsExplorer component
 * with sample data and callbacks.
 */

import QuestionsExplorer, {
	type QuestionsExplorerItem,
} from "./QuestionsExplorer";

// Sample data - now with 50 items to demonstrate pagination and dataset filtering
const sampleItems: QuestionsExplorerItem[] = [
	{
		id: "gt-001",
		question: "What is the capital of France?",
		answer: "Paris",
		status: "approved",
		providerId: "json",
		views: 150,
		reuses: 12,
		datasetName: "geography",
		tags: ["beginner", "popular"],
		reviewedAt: "2025-09-15T10:30:00Z",
	},
	{
		id: "gt-002",
		question: "How does photosynthesis work?",
		answer: "Photosynthesis converts light energy into chemical energy...",
		status: "draft",
		providerId: "json",
		views: 45,
		reuses: 3,
		datasetName: "biology",
		tags: ["science", "beginner"],
		reviewedAt: "2025-09-20T14:20:00Z",
	},
	{
		id: "gt-003",
		question: "What is quantum computing?",
		answer: "Quantum computing uses quantum-mechanical phenomena...",
		status: "approved",
		providerId: "json",
		views: 230,
		reuses: 28,
		datasetName: "technology",
		tags: ["advanced", "technical", "popular"],
		reviewedAt: "2025-09-10T08:15:00Z",
	},
	{
		id: "gt-004",
		question: "Explain machine learning basics",
		answer: "Machine learning is a subset of artificial intelligence...",
		status: "deleted",
		providerId: "json",
		views: 89,
		reuses: 7,
		datasetName: "technology",
		tags: ["technical", "AI"],
		reviewedAt: "2025-08-25T16:45:00Z",
	},
	{
		id: "gt-005",
		question: "What are the benefits of exercise?",
		answer: "Regular exercise improves cardiovascular health...",
		status: "approved",
		providerId: "json",
		views: 320,
		reuses: 41,
		datasetName: "health",
		tags: ["beginner", "wellness"],
		reviewedAt: "2025-09-22T11:00:00Z",
	},
	{
		id: "gt-006",
		question: "How do neural networks work?",
		answer:
			"Neural networks are computing systems inspired by biological neural networks...",
		status: "draft",
		providerId: "json",
		views: 198,
		reuses: 15,
		datasetName: "technology",
		tags: ["advanced", "technical", "AI"],
		reviewedAt: "2025-09-18T09:30:00Z",
	},
	{
		id: "gt-007",
		question: "What is blockchain technology?",
		answer: "Blockchain is a distributed ledger technology...",
		status: "approved",
		providerId: "json",
		views: 412,
		reuses: 52,
		datasetName: "technology",
		tags: ["popular", "technical"],
		reviewedAt: "2025-09-12T14:22:00Z",
	},
	{
		id: "gt-008",
		question: "Explain the water cycle",
		answer: "The water cycle describes the continuous movement of water...",
		status: "approved",
		providerId: "json",
		views: 276,
		reuses: 34,
		datasetName: "science",
		tags: ["beginner", "science"],
		reviewedAt: "2025-09-05T10:10:00Z",
	},
	{
		id: "gt-009",
		question: "What causes climate change?",
		answer: "Climate change is primarily caused by greenhouse gas emissions...",
		status: "draft",
		providerId: "json",
		views: 523,
		reuses: 67,
		datasetName: "science",
		tags: ["science", "popular", "environmental"],
		reviewedAt: "2025-09-28T15:45:00Z",
	},
	{
		id: "gt-010",
		question: "How does DNA replication work?",
		answer: "DNA replication is the process of copying DNA molecules...",
		status: "approved",
		providerId: "json",
		views: 145,
		reuses: 18,
		datasetName: "biology",
		tags: ["science", "advanced"],
		reviewedAt: "2025-09-08T13:20:00Z",
	},
	{
		id: "gt-011",
		question: "What is the theory of relativity?",
		answer:
			"Einstein's theory of relativity revolutionized our understanding of space and time...",
		status: "approved",
		providerId: "json",
		views: 387,
		reuses: 45,
		datasetName: "physics",
		tags: ["advanced", "science", "popular"],
		reviewedAt: "2025-09-14T07:30:00Z",
	},
	{
		id: "gt-012",
		question: "How do vaccines work?",
		answer:
			"Vaccines work by training the immune system to recognize pathogens...",
		status: "draft",
		providerId: "json",
		views: 612,
		reuses: 78,
		datasetName: "health",
		reviewedAt: "2025-09-25T16:15:00Z",
	},
	{
		id: "gt-013",
		question: "What is cloud computing?",
		answer: "Cloud computing delivers computing services over the internet...",
		status: "deleted",
		providerId: "json",
		views: 298,
		reuses: 39,
		datasetName: "technology",
		reviewedAt: "2025-08-30T12:00:00Z",
	},
	{
		id: "gt-014",
		question: "Explain Newton's laws of motion",
		answer:
			"Newton's three laws describe the relationship between objects and forces...",
		status: "approved",
		providerId: "json",
		views: 165,
		reuses: 21,
		datasetName: "physics",
		reviewedAt: "2025-09-03T09:45:00Z",
	},
	{
		id: "gt-015",
		question: "What is artificial intelligence?",
		answer: "AI is the simulation of human intelligence by machines...",
		status: "draft",
		providerId: "json",
		views: 734,
		reuses: 91,
		datasetName: "technology",
		reviewedAt: "2025-09-29T18:00:00Z",
	},
	{
		id: "gt-016",
		question: "How do black holes form?",
		answer:
			"Black holes form when massive stars collapse at the end of their life cycle...",
		status: "approved",
		providerId: "json",
		views: 445,
		reuses: 56,
		datasetName: "physics",
		reviewedAt: "2025-09-11T11:20:00Z",
	},
	{
		id: "gt-017",
		question: "What is cryptocurrency?",
		answer: "Cryptocurrency is a digital currency secured by cryptography...",
		status: "draft",
		providerId: "json",
		views: 521,
		reuses: 64,
		datasetName: "technology",
		reviewedAt: "2025-09-27T10:30:00Z",
	},
	{
		id: "gt-018",
		question: "Explain the concept of entropy",
		answer: "Entropy is a measure of disorder or randomness in a system...",
		status: "approved",
		providerId: "json",
		views: 187,
		reuses: 23,
		datasetName: "physics",
		reviewedAt: "2025-09-06T14:50:00Z",
	},
	{
		id: "gt-019",
		question: "What are stem cells?",
		answer:
			"Stem cells are undifferentiated cells capable of developing into various cell types...",
		status: "draft",
		providerId: "json",
		views: 354,
		reuses: 42,
		datasetName: "biology",
		reviewedAt: "2025-09-19T08:15:00Z",
	},
	{
		id: "gt-020",
		question: "How does the internet work?",
		answer: "The internet is a global network of interconnected computers...",
		status: "approved",
		providerId: "json",
		views: 289,
		reuses: 37,
		datasetName: "technology",
		reviewedAt: "2025-09-13T16:40:00Z",
	},
	{
		id: "gt-021",
		question: "What is natural selection?",
		answer:
			"Natural selection is the process by which organisms better adapted survive...",
		status: "approved",
		providerId: "json",
		views: 423,
		reuses: 54,
		datasetName: "biology",
		reviewedAt: "2025-09-16T12:30:00Z",
	},
	{
		id: "gt-022",
		question: "Explain quantum entanglement",
		answer:
			"Quantum entanglement is a phenomenon where particles remain connected...",
		status: "draft",
		providerId: "json",
		views: 267,
		reuses: 31,
		datasetName: "physics",
		reviewedAt: "2025-09-21T09:00:00Z",
	},
	{
		id: "gt-023",
		question: "What causes earthquakes?",
		answer:
			"Earthquakes occur when energy is released from tectonic plate movements...",
		status: "deleted",
		providerId: "json",
		views: 198,
		reuses: 25,
		datasetName: "science",
		reviewedAt: "2025-08-28T15:20:00Z",
	},
	{
		id: "gt-024",
		question: "How do solar panels work?",
		answer:
			"Solar panels convert sunlight into electricity using photovoltaic cells...",
		status: "approved",
		providerId: "json",
		views: 512,
		reuses: 66,
		datasetName: "technology",
		reviewedAt: "2025-09-17T13:45:00Z",
	},
	{
		id: "gt-025",
		question: "What is gene editing?",
		answer: "Gene editing allows scientists to modify DNA sequences...",
		status: "draft",
		providerId: "json",
		views: 389,
		reuses: 48,
		datasetName: "biology",
		reviewedAt: "2025-09-24T11:10:00Z",
	},
	{
		id: "gt-026",
		question: "Explain the greenhouse effect",
		answer:
			"The greenhouse effect is the warming of Earth's surface and atmosphere...",
		status: "approved",
		providerId: "json",
		views: 456,
		reuses: 58,
		datasetName: "science",
		reviewedAt: "2025-09-09T10:25:00Z",
	},
	{
		id: "gt-027",
		question: "What is machine vision?",
		answer:
			"Machine vision enables computers to interpret visual information...",
		status: "draft",
		providerId: "json",
		views: 312,
		reuses: 38,
		datasetName: "technology",
		reviewedAt: "2025-09-23T14:00:00Z",
	},
	{
		id: "gt-028",
		question: "How does GPS work?",
		answer: "GPS uses satellites to determine precise location on Earth...",
		status: "approved",
		providerId: "json",
		views: 234,
		reuses: 29,
		datasetName: "technology",
		reviewedAt: "2025-09-07T08:40:00Z",
	},
	{
		id: "gt-029",
		question: "What are exoplanets?",
		answer:
			"Exoplanets are planets that orbit stars outside our solar system...",
		status: "approved",
		providerId: "json",
		views: 378,
		reuses: 47,
		datasetName: "physics",
		reviewedAt: "2025-09-14T16:55:00Z",
	},
	{
		id: "gt-030",
		question: "Explain nuclear fusion",
		answer: "Nuclear fusion is the process that powers the sun...",
		status: "draft",
		providerId: "json",
		views: 521,
		reuses: 63,
		datasetName: "physics",
		reviewedAt: "2025-09-26T09:30:00Z",
	},
	{
		id: "gt-031",
		question: "What is nanotechnology?",
		answer:
			"Nanotechnology involves manipulating matter at the atomic scale...",
		status: "approved",
		providerId: "json",
		views: 267,
		reuses: 33,
		datasetName: "technology",
		reviewedAt: "2025-09-04T12:15:00Z",
	},
	{
		id: "gt-032",
		question: "How do antibiotics work?",
		answer: "Antibiotics kill or inhibit the growth of bacteria...",
		status: "draft",
		providerId: "json",
		views: 445,
		reuses: 55,
		datasetName: "health",
		reviewedAt: "2025-09-20T17:30:00Z",
	},
	{
		id: "gt-033",
		question: "What is dark matter?",
		answer:
			"Dark matter is an invisible form of matter that makes up most of the universe...",
		status: "approved",
		providerId: "json",
		views: 598,
		reuses: 72,
		datasetName: "physics",
		reviewedAt: "2025-09-15T11:45:00Z",
	},
	{
		id: "gt-034",
		question: "Explain the Big Bang theory",
		answer: "The Big Bang theory describes the origin of the universe...",
		status: "approved",
		providerId: "json",
		views: 487,
		reuses: 61,
		datasetName: "physics",
		reviewedAt: "2025-09-12T09:20:00Z",
	},
	{
		id: "gt-035",
		question: "What is cybersecurity?",
		answer: "Cybersecurity protects computer systems from digital attacks...",
		status: "draft",
		providerId: "json",
		views: 623,
		reuses: 79,
		datasetName: "technology",
		reviewedAt: "2025-09-28T13:50:00Z",
	},
	{
		id: "gt-036",
		question: "How does the human brain work?",
		answer: "The brain processes information through billions of neurons...",
		status: "approved",
		providerId: "json",
		views: 712,
		reuses: 88,
		datasetName: "biology",
		reviewedAt: "2025-09-19T15:10:00Z",
	},
	{
		id: "gt-037",
		question: "What is 5G technology?",
		answer: "5G is the fifth generation of cellular network technology...",
		status: "draft",
		providerId: "json",
		views: 356,
		reuses: 44,
		datasetName: "technology",
		reviewedAt: "2025-09-25T10:05:00Z",
	},
	{
		id: "gt-038",
		question: "Explain plate tectonics",
		answer:
			"Plate tectonics describes the movement of Earth's lithospheric plates...",
		status: "approved",
		providerId: "json",
		views: 298,
		reuses: 36,
		datasetName: "science",
		reviewedAt: "2025-09-08T14:25:00Z",
	},
	{
		id: "gt-039",
		question: "What is renewable energy?",
		answer: "Renewable energy comes from naturally replenishing sources...",
		status: "approved",
		providerId: "json",
		views: 534,
		reuses: 68,
		datasetName: "science",
		reviewedAt: "2025-09-16T16:40:00Z",
	},
	{
		id: "gt-040",
		question: "How do batteries work?",
		answer: "Batteries convert chemical energy into electrical energy...",
		status: "draft",
		providerId: "json",
		views: 412,
		reuses: 51,
		datasetName: "technology",
		reviewedAt: "2025-09-22T11:55:00Z",
	},
	{
		id: "gt-041",
		question: "What is the immune system?",
		answer: "The immune system defends the body against harmful pathogens...",
		status: "approved",
		providerId: "json",
		views: 467,
		reuses: 59,
		datasetName: "health",
		reviewedAt: "2025-09-11T13:20:00Z",
	},
	{
		id: "gt-042",
		question: "Explain deep learning",
		answer: "Deep learning uses neural networks with multiple layers...",
		status: "draft",
		providerId: "json",
		views: 589,
		reuses: 73,
		datasetName: "technology",
		reviewedAt: "2025-09-27T15:35:00Z",
	},
	{
		id: "gt-043",
		question: "What is bioengineering?",
		answer:
			"Bioengineering applies engineering principles to biological systems...",
		status: "approved",
		providerId: "json",
		views: 321,
		reuses: 40,
		datasetName: "biology",
		reviewedAt: "2025-09-10T10:50:00Z",
	},
	{
		id: "gt-044",
		question: "How do superconductors work?",
		answer:
			"Superconductors conduct electricity with zero resistance at low temperatures...",
		status: "draft",
		providerId: "json",
		views: 245,
		reuses: 30,
		datasetName: "physics",
		reviewedAt: "2025-09-18T12:05:00Z",
	},
	{
		id: "gt-045",
		question: "What is augmented reality?",
		answer: "AR overlays digital information onto the real world...",
		status: "approved",
		providerId: "json",
		views: 678,
		reuses: 84,
		datasetName: "technology",
		reviewedAt: "2025-09-24T14:15:00Z",
	},
	{
		id: "gt-046",
		question: "Explain the carbon cycle",
		answer: "The carbon cycle describes how carbon moves through ecosystems...",
		status: "approved",
		providerId: "json",
		views: 334,
		reuses: 42,
		datasetName: "science",
		reviewedAt: "2025-09-13T09:30:00Z",
	},
	{
		id: "gt-047",
		question: "What is quantum computing used for?",
		answer:
			"Quantum computers solve complex problems beyond classical computers...",
		status: "draft",
		providerId: "json",
		views: 501,
		reuses: 62,
		datasetName: "technology",
		reviewedAt: "2025-09-29T11:45:00Z",
	},
	{
		id: "gt-048",
		question: "How does protein synthesis work?",
		answer:
			"Protein synthesis involves transcription and translation of genetic code...",
		status: "approved",
		providerId: "json",
		views: 287,
		reuses: 35,
		datasetName: "biology",
		reviewedAt: "2025-09-06T16:00:00Z",
	},
	{
		id: "gt-049",
		question: "What is edge computing?",
		answer: "Edge computing processes data closer to where it's generated...",
		status: "draft",
		providerId: "json",
		views: 423,
		reuses: 53,
		datasetName: "technology",
		reviewedAt: "2025-09-21T13:10:00Z",
	},
	{
		id: "gt-050",
		question: "Explain the Doppler effect",
		answer:
			"The Doppler effect is the change in frequency due to relative motion...",
		status: "approved",
		providerId: "json",
		views: 198,
		reuses: 24,
		datasetName: "physics",
		reviewedAt: "2025-09-05T11:25:00Z",
	},
];

export default function QuestionsExplorerExample() {
	const handleAssign = (item: QuestionsExplorerItem) => {
		console.log(`Assign ground truth: ${item.id}`);
		// Implementation: Open assignment modal or navigate to assignment flow
		alert(`Assign functionality for ${item.id} would be triggered here`);
	};

	const handleInspect = (item: QuestionsExplorerItem) => {
		console.log(`Inspect ground truth: ${item.id}`);
		// Implementation: Open detail view or navigate to editor
		alert(`Inspect functionality for ${item.id} would be triggered here`);
	};

	const handleDelete = (item: QuestionsExplorerItem) => {
		console.log(`Delete ground truth: ${item.id}`);
		// Implementation: Confirm and perform soft delete
		const confirmed = window.confirm(
			`Are you sure you want to delete ${item.id}?`,
		);
		if (confirmed) {
			alert(`Delete functionality for ${item.id} would be triggered here`);
		}
	};

	return (
		<div className="flex h-full flex-col">
			<QuestionsExplorer
				items={sampleItems}
				onAssign={handleAssign}
				onInspect={handleInspect}
				onDelete={handleDelete}
				className="flex-1 min-h-0"
			/>
		</div>
	);
}
