/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         *  Healthz
         * @description Health check endpoint for ACA liveness/readiness probes.
         */
        get: operations["_healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Frontend Config
         * @description Get frontend runtime configuration.
         *
         *     This endpoint exposes backend configuration to the frontend,
         *     allowing runtime configuration without rebuilding the frontend.
         *
         *     Returns:
         *         FrontendConfig: Configuration values for frontend validation behavior
         */
        get: operations["get_frontend_config_v1_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ground-truths/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Stats */
        get: operations["get_stats_v1_ground_truths_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ground-truths": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List All Ground Truths */
        get: operations["list_all_ground_truths_v1_ground_truths_get"];
        put?: never;
        /**
         * Import Bulk
         * @description Bulk import ground truth items.
         *
         *     Behavior:
         *     - ID field: Each item may include 'id' (alias 'uuid'); missing/blank values are generated server-side using
         *       randomname to produce a two-word, hyphenated string (e.g., 'sleek-voxel').
         *     - Order preservation: Response `uuids` mirrors request order for easy correlation.
         *     - Duplicate handling: Existing items are not overwritten; per-item errors are returned in `errors`.
         *     - Optional approval: `approve=true` marks all items approved and sets review metadata.
         */
        post: operations["import_bulk_v1_ground_truths_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ground-truths/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Snapshot
         * @description Return approved items as a downloadable JSON attachment.
         *
         *     Response headers include Content-Disposition so browsers download the file.
         */
        get: operations["download_snapshot_v1_ground_truths_snapshot_get"];
        put?: never;
        /** Snapshot */
        post: operations["snapshot_v1_ground_truths_snapshot_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ground-truths/{datasetName}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Ground Truths */
        get: operations["list_ground_truths_v1_ground_truths__datasetName__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ground-truths/{datasetName}/{bucket}/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ground Truth */
        get: operations["get_ground_truth_v1_ground_truths__datasetName___bucket___item_id__get"];
        /** Update Ground Truth */
        put: operations["update_ground_truth_v1_ground_truths__datasetName___bucket___item_id__put"];
        post?: never;
        /**
         * Delete Item
         * @description Soft-delete a ground truth item.
         */
        delete: operations["delete_item_v1_ground_truths__datasetName___bucket___item_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ground-truths/recompute-tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Recompute Computed Tags
         * @description Recompute computed tags for all matching ground truth items.
         *
         *     This endpoint recalculates the `computedTags` field for all items matching
         *     the optional filter criteria. Use this when:
         *     - A new computed tag plugin has been added
         *     - An existing plugin's logic has been modified
         *     - Data needs to be reprocessed after a bug fix
         *
         *     The operation is idempotent - running it multiple times with the same
         *     data produces the same result.
         *
         *     **Important**: By default, `dry_run=true` for safety. Set `dry_run=false`
         *     to actually persist changes.
         */
        post: operations["recompute_computed_tags_v1_ground_truths_recompute_tags_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/assignments/self-serve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Self Serve Assignments */
        post: operations["self_serve_assignments_v1_assignments_self_serve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/assignments/my": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List My Assignments */
        get: operations["list_my_assignments_v1_assignments_my_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/assignments/{dataset}/{bucket}/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Item */
        put: operations["update_item_v1_assignments__dataset___bucket___item_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/assignments/{dataset}/{bucket}/{item_id}/assign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Assign Item
         * @description Assign a specific ground truth item to the current user.
         *
         *     This endpoint:
         *     - Assigns the item to the current user
         *     - Sets the item status to draft (even if previously approved/deleted/skipped)
         *     - Creates an assignment document in the assignments container
         *     - Returns the updated ground truth item
         *
         *     With force=true:
         *     - Requires admin or team-lead role
         *     - Allows taking over items assigned to other users
         *     - Cleans up the previous user's assignment document
         */
        post: operations["assign_item_v1_assignments__dataset___bucket___item_id__assign_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/assignments/{dataset}/{bucket}/{item_id}/duplicate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Duplicate Assignment Item
         * @description Duplicate an existing item as a draft rephrase, assign to caller, and return the new item.
         */
        post: operations["duplicate_assignment_item_v1_assignments__dataset___bucket___item_id__duplicate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/schemas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Schemas
         * @description List available component schema names from the OpenAPI document.
         *
         *     Compatibility behavior:
         *     - Returns a list where the first segment contains objects with `name` and `title`
         *         (for newer clients/tests that expect objects), followed by the plain string names
         *         (to preserve backward-compatibility with older callers/tests).
         */
        get: operations["list_schemas_v1_schemas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/schemas/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Schema
         * @description Return a specific component schema by name from the OpenAPI document.
         */
        get: operations["get_schema_v1_schemas__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tags/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Tags Schema */
        get: operations["get_tags_schema_v1_tags_schema_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Tags */
        get: operations["get_tags_v1_tags_get"];
        put?: never;
        /** Post Tags */
        post: operations["post_tags_v1_tags_post"];
        /** Delete Tags */
        delete: operations["delete_tags_v1_tags_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tags/glossary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Tags Glossary
         * @description Returns comprehensive tag glossary with definitions from all sources.
         */
        get: operations["get_tags_glossary_v1_tags_glossary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tags/definitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Tag Definition
         * @description Create or update a custom tag definition.
         *
         *     Note: In production, user_id should be obtained from authentication (e.g., via Depends(get_current_user)).
         *     For now, we use a default value to keep the implementation simple.
         */
        post: operations["create_tag_definition_v1_tags_definitions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tags/definitions/{tag_key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Tag Definition
         * @description Delete a custom tag definition by tag_key.
         */
        delete: operations["delete_tag_definition_v1_tags_definitions__tag_key__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Datasets */
        get: operations["list_datasets_v1_datasets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/datasets/{datasetName}/curation-instructions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Curation Instructions */
        get: operations["get_curation_instructions_v1_datasets__datasetName__curation_instructions_get"];
        /** Put Curation Instructions */
        put: operations["put_curation_instructions_v1_datasets__datasetName__curation_instructions_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/datasets/{datasetName}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Dataset
         * @description Hard-delete a dataset.
         */
        delete: operations["delete_dataset_v1_datasets__datasetName__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_v1_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddTagsRequest */
        AddTagsRequest: {
            /** Tags */
            tags: string[];
        };
        /**
         * AgenticGroundTruthEntry
         * @description Generic agentic-first host model.
         *
         *     The core contract intentionally exposes only the generic schema in OpenAPI. Legacy
         *     RAG-shaped payloads are translated into this shape when validating this base class so
         *     existing data can be carried forward without remaining top-level contract fields.
         */
        "AgenticGroundTruthEntry-Input": {
            /** Id */
            id: string;
            /** Datasetname */
            datasetName: string;
            /** Bucket */
            bucket?: string | null;
            /** @default draft */
            status: components["schemas"]["GroundTruthStatus"];
            /**
             * Doctype
             * @default ground-truth-item
             */
            docType: string;
            /**
             * Schemaversion
             * @default v2
             */
            schemaVersion: string;
            /** Manualtags */
            manualTags?: string[];
            /** Computedtags */
            computedTags?: string[];
            /**
             * Comment
             * @default
             */
            comment: string;
            /** Assignedto */
            assignedTo?: string | null;
            /** Assignedat */
            assignedAt?: string | null;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt?: string;
            /** Updatedby */
            updatedBy?: string | null;
            /** Reviewedat */
            reviewedAt?: string | null;
            /** Etag */
            _etag?: string | null;
            /**
             * Scenarioid
             * @default
             */
            scenarioId: string;
            /** History */
            history?: components["schemas"]["HistoryEntry"][];
            /** Contextentries */
            contextEntries?: components["schemas"]["ContextEntry"][];
            /** Traceids */
            traceIds?: {
                [key: string]: string;
            } | null;
            /** Toolcalls */
            toolCalls?: components["schemas"]["ToolCallRecord"][];
            expectedTools?: components["schemas"]["ExpectedTools"];
            /** Feedback */
            feedback?: components["schemas"]["FeedbackEntry"][];
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /** Plugins */
            plugins?: {
                [key: string]: components["schemas"]["PluginPayload"];
            };
            /** Createdby */
            createdBy?: string | null;
            /** Createdat */
            createdAt?: string | null;
            /** Tracepayload */
            tracePayload?: {
                [key: string]: unknown;
            };
        };
        /**
         * AgenticGroundTruthEntry
         * @description Generic agentic-first host model.
         *
         *     The core contract intentionally exposes only the generic schema in OpenAPI. Legacy
         *     RAG-shaped payloads are translated into this shape when validating this base class so
         *     existing data can be carried forward without remaining top-level contract fields.
         */
        "AgenticGroundTruthEntry-Output": {
            /** Id */
            id: string;
            /** Datasetname */
            datasetName: string;
            /** Bucket */
            bucket?: string | null;
            /** @default draft */
            status: components["schemas"]["GroundTruthStatus"];
            /**
             * Doctype
             * @default ground-truth-item
             */
            docType: string;
            /**
             * Schemaversion
             * @default v2
             */
            schemaVersion: string;
            /** Manualtags */
            manualTags?: string[];
            /** Computedtags */
            computedTags?: string[];
            /**
             * Comment
             * @default
             */
            comment: string;
            /** Assignedto */
            assignedTo?: string | null;
            /** Assignedat */
            assignedAt?: string | null;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt?: string;
            /** Updatedby */
            updatedBy?: string | null;
            /** Reviewedat */
            reviewedAt?: string | null;
            /** Etag */
            _etag?: string | null;
            /**
             * Scenarioid
             * @default
             */
            scenarioId: string;
            /** History */
            history?: components["schemas"]["HistoryEntry"][];
            /** Contextentries */
            contextEntries?: components["schemas"]["ContextEntry"][];
            /** Traceids */
            traceIds?: {
                [key: string]: string;
            } | null;
            /** Toolcalls */
            toolCalls?: components["schemas"]["ToolCallRecord"][];
            expectedTools?: components["schemas"]["ExpectedTools"];
            /** Feedback */
            feedback?: components["schemas"]["FeedbackEntry"][];
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /** Plugins */
            plugins?: {
                [key: string]: components["schemas"]["PluginPayload"];
            };
            /** Createdby */
            createdBy?: string | null;
            /** Createdat */
            createdAt?: string | null;
            /** Tracepayload */
            tracePayload?: {
                [key: string]: unknown;
            };
            /** Tags */
            readonly tags: string[];
        };
        /**
         * AssignItemRequest
         * @description Request body for assignment endpoint.
         */
        AssignItemRequest: {
            /**
             * Force
             * @description Force assignment even if item is assigned to another user (requires admin or team-lead role)
             * @default false
             */
            force: boolean;
        };
        /** AssignmentUpdateRequest */
        AssignmentUpdateRequest: {
            /** Comment */
            comment?: string | null;
            /** Status */
            status?: components["schemas"]["GroundTruthStatus"] | string;
            /** Manualtags */
            manualTags?: string[] | null;
            /** Approve */
            approve?: boolean | null;
            /** Etag */
            etag?: string | null;
            /** History */
            history?: components["schemas"]["HistoryEntryPatch"][] | null;
            /** Contextentries */
            contextEntries?: components["schemas"]["ContextEntry"][] | null;
            /** Toolcalls */
            toolCalls?: components["schemas"]["ToolCallRecord"][] | null;
            /** Expectedtools */
            expectedTools?: components["schemas"]["ExpectedTools"];
            /** Feedback */
            feedback?: components["schemas"]["FeedbackEntry"][] | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            } | null;
            /** Plugins */
            plugins?: {
                [key: string]: components["schemas"]["PluginPayload"];
            } | null;
            /** Traceids */
            traceIds?: {
                [key: string]: string;
            } | null;
            /** Tracepayload */
            tracePayload?: {
                [key: string]: unknown;
            } | null;
            /** Scenarioid */
            scenarioId?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** BulkImportError */
        BulkImportError: {
            /**
             * Index
             * @description 0-based position in request array
             */
            index: number;
            /**
             * Itemid
             * @description ID of the failed item (if available)
             */
            itemId?: string | null;
            /**
             * Field
             * @description Field that caused the error (if applicable)
             */
            field?: string | null;
            /**
             * Code
             * @description Error code: INVALID_TAG, DUPLICATE_ID, CREATE_FAILED, etc.
             */
            code: string;
            /**
             * Message
             * @description Human-readable error description
             */
            message: string;
        };
        /** ContextEntry */
        ContextEntry: {
            /** Key */
            key: string;
            /** Value */
            value: unknown;
        };
        /** CurationInstructionsUpdate */
        CurationInstructionsUpdate: {
            /** Instructions */
            instructions: string;
            /** Etag */
            _etag?: string | null;
        };
        /** DatasetCurationInstructions */
        DatasetCurationInstructions: {
            /** Id */
            id: string;
            /** Datasetname */
            datasetName: string;
            /**
             * Bucket
             * Format: uuid
             */
            bucket?: string;
            /**
             * Doctype
             * @default curation-instructions
             */
            docType: string;
            /**
             * Schemaversion
             * @default v1
             */
            schemaVersion: string;
            /** Instructions */
            instructions: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt?: string;
            /** Updatedby */
            updatedBy?: string | null;
            /** Etag */
            _etag?: string | null;
        };
        /** DependencyDTO */
        DependencyDTO: {
            /** Group */
            group: string;
            /** Value */
            value: string;
        };
        /**
         * DuplicateWarning
         * @description Warning about a likely duplicate of an approved item.
         */
        DuplicateWarning: {
            /**
             * Itemid
             * @description Draft item identifier
             */
            itemId: string;
            /**
             * Duplicateid
             * @description ID of the likely duplicate approved item
             */
            duplicateId: string;
            /**
             * Duplicatequestion
             * @description Question text from the duplicate item
             */
            duplicateQuestion: string;
            /**
             * Duplicatestatus
             * @description Status of the duplicate item
             */
            duplicateStatus: string;
            /**
             * Matchreason
             * @description Why this was flagged as a duplicate (e.g., 'exact question match', 'question and answer match')
             */
            matchReason: string;
        };
        /**
         * ExpectedTools
         * @description Tool expectations. Tools are implicitly allowed unless listed here.
         */
        ExpectedTools: {
            /** Required */
            required?: components["schemas"]["ToolExpectation"][];
            /** Optional */
            optional?: components["schemas"]["ToolExpectation"][];
            /** Notneeded */
            notNeeded?: components["schemas"]["ToolExpectation"][];
        };
        /** ExportDeliveryOptions */
        ExportDeliveryOptions: {
            /**
             * Mode
             * @default artifact
             * @enum {string}
             */
            mode: "attachment" | "artifact";
        };
        /** ExportFilters */
        ExportFilters: {
            /** Datasetnames */
            datasetNames?: string[] | null;
            /**
             * Status
             * @default approved
             */
            status: string;
        };
        /** FeedbackEntry */
        FeedbackEntry: {
            /**
             * Source
             * @default
             */
            source: string;
            /** Values */
            values?: {
                [key: string]: unknown;
            };
        };
        /**
         * FrontendConfig
         * @description Frontend runtime configuration.
         */
        FrontendConfig: {
            /** Requirereferencevisit */
            requireReferenceVisit: boolean;
            /** Requirekeyparagraph */
            requireKeyParagraph: boolean;
            /** Selfservelimit */
            selfServeLimit: number;
            /** Trustedreferencedomains */
            trustedReferenceDomains: string[];
        };
        /** GlossaryResponse */
        GlossaryResponse: {
            /**
             * Version
             * @default v1
             */
            version: string;
            /** Groups */
            groups: components["schemas"]["TagGroupGlossaryDTO"][];
        };
        /** GroundTruthListResponse */
        GroundTruthListResponse: {
            /** Items */
            items: components["schemas"]["AgenticGroundTruthEntry-Output"][];
            pagination: components["schemas"]["PaginationMetadata"];
        };
        /**
         * GroundTruthStatus
         * @enum {string}
         */
        GroundTruthStatus: "draft" | "approved" | "deleted" | "skipped";
        /** GroundTruthUpdateRequest */
        GroundTruthUpdateRequest: {
            /** Status */
            status?: components["schemas"]["GroundTruthStatus"] | string;
            /** Comment */
            comment?: string | null;
            /** History */
            history?: components["schemas"]["HistoryEntryPatch"][] | null;
            /** Contextentries */
            contextEntries?: components["schemas"]["ContextEntry"][] | null;
            /** Toolcalls */
            toolCalls?: components["schemas"]["ToolCallRecord"][] | null;
            /** Expectedtools */
            expectedTools?: components["schemas"]["ExpectedTools"];
            /** Feedback */
            feedback?: components["schemas"]["FeedbackEntry"][] | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            } | null;
            /** Plugins */
            plugins?: {
                [key: string]: components["schemas"]["PluginPayload"];
            } | null;
            /** Manualtags */
            manualTags?: string[] | null;
            /** Traceids */
            traceIds?: {
                [key: string]: string;
            } | null;
            /** Tracepayload */
            tracePayload?: {
                [key: string]: unknown;
            } | null;
            /** Scenarioid */
            scenarioId?: string | null;
            /** Etag */
            etag?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HistoryEntry */
        HistoryEntry: {
            /** Role */
            role: string;
            /** Msg */
            msg: string;
        };
        /** HistoryEntryPatch */
        HistoryEntryPatch: {
            /** Role */
            role: string;
            /** Msg */
            msg?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** ImportBulkResponse */
        ImportBulkResponse: {
            /**
             * Imported
             * @description Number of items successfully imported.
             */
            imported: number;
            /**
             * Failed
             * @description Number of items that failed to import.
             * @default 0
             */
            failed: number;
            /**
             * Errors
             * @description Structured error objects for items that failed to import.
             */
            errors?: components["schemas"]["BulkImportError"][];
            /**
             * Uuids
             * @description The item IDs in the same order as the request payload. Clients may send either 'id' or 'uuid' in each item; when missing or blank, the server generates a two-word, hyphenated string ID (e.g., 'sleek-voxel') via randomname.
             */
            uuids?: string[];
            /**
             * Piiwarnings
             * @description Warnings about potential personally identifiable information (PII) detected in imported items. These are informational only and do not block import. Review flagged content for remediation.
             */
            piiWarnings?: components["schemas"]["PIIWarning"][];
            /**
             * Duplicatewarnings
             * @description Warnings about draft items that appear to be duplicates of approved items. These are informational only and do not block import. Review for potential duplicates.
             */
            duplicateWarnings?: components["schemas"]["DuplicateWarning"][];
            /** @description Summary statistics for the bulk import operation. */
            validationSummary: components["schemas"]["ValidationSummary"];
        };
        /**
         * PIIWarning
         * @description Warning about potential PII detected in a ground truth item.
         */
        PIIWarning: {
            /**
             * Item Id
             * @description Item identifier
             */
            item_id: string;
            /**
             * Field
             * @description Field name where the PII was detected (e.g., 'history.question', 'history[2].msg')
             */
            field: string;
            /**
             * Pattern Type
             * @description Type of PII detected ('email' or 'phone')
             */
            pattern_type: string;
            /**
             * Snippet
             * @description Masked context snippet showing the detected PII
             */
            snippet: string;
            /**
             * Position
             * @description Character position where the PII was found
             */
            position: number;
        };
        /** PaginationMetadata */
        PaginationMetadata: {
            /**
             * Page
             * @description Current page number (1-indexed)
             */
            page: number;
            /**
             * Limit
             * @description Items per page
             */
            limit: number;
            /**
             * Total
             * @description Total number of items matching filters
             */
            total: number;
            /**
             * Totalpages
             * @description Total number of pages
             */
            totalPages: number;
            /**
             * Hasnext
             * @description Whether there is a next page
             */
            hasNext: boolean;
            /**
             * Hasprev
             * @description Whether there is a previous page
             */
            hasPrev: boolean;
        };
        /** PluginPayload */
        PluginPayload: {
            /** Kind */
            kind: string;
            /**
             * Version
             * @default 1.0
             */
            version: string;
            /** Data */
            data?: {
                [key: string]: unknown;
            };
        };
        /**
         * RecomputeTagsResponse
         * @description Response for bulk computed tag recomputation.
         */
        RecomputeTagsResponse: {
            /**
             * Total
             * @description Total items matching the filter criteria.
             */
            total: number;
            /**
             * Processed
             * @description Number of items successfully processed.
             */
            processed: number;
            /**
             * Updated
             * @description Number of items with changed computed tags.
             */
            updated: number;
            /**
             * Skipped
             * @description Number of items with unchanged computed tags.
             */
            skipped: number;
            /**
             * Errors
             * @description Error messages for failed items.
             */
            errors?: string[];
            /**
             * Dry Run
             * @description Whether this was a dry run (no changes persisted).
             */
            dry_run: boolean;
            /**
             * Duration Ms
             * @description Operation duration in milliseconds.
             */
            duration_ms: number;
        };
        /** RemoveTagsRequest */
        RemoveTagsRequest: {
            /** Tags */
            tags: string[];
        };
        /** SelfServeResponse */
        SelfServeResponse: {
            /** Assigned */
            assigned: components["schemas"]["AgenticGroundTruthEntry-Output"][];
            /** Requested */
            requested: number;
            /** Assignedcount */
            assignedCount: number;
        };
        /** SnapshotExportRequest */
        SnapshotExportRequest: {
            /** Format */
            format?: ("json_snapshot_payload" | "json_items") | null;
            filters?: components["schemas"]["ExportFilters"] | null;
            /** Processors */
            processors?: string[] | null;
            delivery?: components["schemas"]["ExportDeliveryOptions"] | null;
        };
        /**
         * SortField
         * @enum {string}
         */
        SortField: "reviewedAt" | "updatedAt" | "id" | "hasAnswer" | "tagCount";
        /**
         * SortOrder
         * @enum {string}
         */
        SortOrder: "asc" | "desc";
        /** TagDefinitionDTO */
        TagDefinitionDTO: {
            /** Key */
            key: string;
            /** Description */
            description?: string | null;
        };
        /**
         * TagDefinitionRequest
         * @description Request model for creating/updating a custom tag definition.
         */
        TagDefinitionRequest: {
            /**
             * Tag Key
             * @description Unique tag key (e.g., 'source:custom_value')
             */
            tag_key: string;
            /**
             * Description
             * @description Human-readable description of the tag
             */
            description: string;
        };
        /**
         * TagDefinitionResponse
         * @description Response model for a custom tag definition.
         */
        TagDefinitionResponse: {
            /** Tag Key */
            tag_key: string;
            /** Description */
            description: string;
            /** Created By */
            created_by: string;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
        };
        /** TagGroupDTO */
        TagGroupDTO: {
            /** Name */
            name: string;
            /** Values */
            values: string[];
            /** Exclusive */
            exclusive: boolean;
            /** Depends On */
            depends_on?: components["schemas"]["DependencyDTO"][];
        };
        /** TagGroupGlossaryDTO */
        TagGroupGlossaryDTO: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Type */
            type: string;
            /** Tags */
            tags: components["schemas"]["TagDefinitionDTO"][];
        };
        /** TagListResponse */
        TagListResponse: {
            /** Tags */
            tags: string[];
            /** Computedtags */
            computedTags?: string[];
        };
        /** TagSchemaResponse */
        TagSchemaResponse: {
            /**
             * Version
             * @default v1
             */
            version: string;
            /** Groups */
            groups: components["schemas"]["TagGroupDTO"][];
        };
        /** ToolCallRecord */
        ToolCallRecord: {
            /**
             * Id
             * @default
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Calltype
             * @default tool
             * @enum {string}
             */
            callType: "tool" | "subagent";
            /** Arguments */
            arguments?: {
                [key: string]: unknown;
            } | null;
            /** Agent */
            agent?: string | null;
            /** Stepnumber */
            stepNumber?: number | null;
            /** Parallelgroup */
            parallelGroup?: string | null;
            /** Parentcallid */
            parentCallId?: string | null;
            /** Response */
            response?: unknown;
        };
        /** ToolExpectation */
        ToolExpectation: {
            /** Name */
            name: string;
            /** Arguments */
            arguments?: {
                [key: string]: unknown;
            } | string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** ValidationSummary */
        ValidationSummary: {
            /**
             * Total
             * @description Total items in request
             */
            total: number;
            /**
             * Succeeded
             * @description Items successfully imported
             */
            succeeded: number;
            /**
             * Failed
             * @description Items that failed
             */
            failed: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    _healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_frontend_config_v1_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrontendConfig"];
                };
            };
        };
    };
    get_stats_v1_ground_truths_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_all_ground_truths_v1_ground_truths_get: {
        parameters: {
            query?: {
                status?: string | null;
                dataset?: string | null;
                tags?: string | null;
                /** @description Comma-separated list of tags to exclude (items with ANY excluded tag will be filtered out) */
                excludeTags?: string | null;
                /** @description Search for items by ID (case-sensitive partial match) */
                itemId?: string | null;
                /** @description Plugin-namespaced filters in key=value form (repeat query param). Example: pluginFilter=rag-compat:refUrl=https://example.com */
                pluginFilter?: string[] | null;
                /** @description Search for items by keyword (case-insensitive text search across questions, answers, and history) */
                keyword?: string | null;
                sortBy?: components["schemas"]["SortField"];
                /** @description Plugin-namespaced sort key, e.g. rag-compat:totalReferences */
                pluginSort?: string | null;
                sortOrder?: components["schemas"]["SortOrder"];
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroundTruthListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_bulk_v1_ground_truths_post: {
        parameters: {
            query?: {
                buckets?: number | null;
                /** @description If true, mark all imported items as approved and set review metadata. */
                approve?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgenticGroundTruthEntry-Input"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportBulkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_snapshot_v1_ground_truths_snapshot_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    snapshot_v1_ground_truths_snapshot_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["SnapshotExportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_ground_truths_v1_ground_truths__datasetName__get: {
        parameters: {
            query?: {
                status?: components["schemas"]["GroundTruthStatus"] | null;
            };
            header?: never;
            path: {
                datasetName: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgenticGroundTruthEntry-Output"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ground_truth_v1_ground_truths__datasetName___bucket___item_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                datasetName: string;
                bucket: string;
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgenticGroundTruthEntry-Output"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_ground_truth_v1_ground_truths__datasetName___bucket___item_id__put: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
            };
            path: {
                datasetName: string;
                bucket: string;
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GroundTruthUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgenticGroundTruthEntry-Output"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_item_v1_ground_truths__datasetName___bucket___item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                datasetName: string;
                bucket: string;
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recompute_computed_tags_v1_ground_truths_recompute_tags_post: {
        parameters: {
            query?: {
                /** @description Filter to items in a specific dataset. If not provided, processes all datasets. */
                dataset?: string | null;
                /** @description Filter to items with a specific status (draft, approved, etc.). */
                status?: components["schemas"]["GroundTruthStatus"] | null;
                /** @description If true, preview changes without persisting. Defaults to true for safety. */
                dry_run?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecomputeTagsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    self_serve_assignments_v1_assignments_self_serve_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SelfServeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_my_assignments_v1_assignments_my_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgenticGroundTruthEntry-Output"][];
                };
            };
        };
    };
    update_item_v1_assignments__dataset___bucket___item_id__put: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
            };
            path: {
                dataset: string;
                bucket: string;
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignmentUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgenticGroundTruthEntry-Output"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assign_item_v1_assignments__dataset___bucket___item_id__assign_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset: string;
                bucket: string;
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AssignItemRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    duplicate_assignment_item_v1_assignments__dataset___bucket___item_id__duplicate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset: string;
                bucket: string;
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgenticGroundTruthEntry-Output"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_schemas_v1_schemas_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": ({
                        [key: string]: string;
                    } | string)[];
                };
            };
        };
    };
    get_schema_v1_schemas__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tags_schema_v1_tags_schema_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagSchemaResponse"];
                };
            };
        };
    };
    get_tags_v1_tags_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagListResponse"];
                };
            };
        };
    };
    post_tags_v1_tags_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddTagsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_tags_v1_tags_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RemoveTagsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tags_glossary_v1_tags_glossary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GlossaryResponse"];
                };
            };
        };
    };
    create_tag_definition_v1_tags_definitions_post: {
        parameters: {
            query?: {
                user_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagDefinitionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagDefinitionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_tag_definition_v1_tags_definitions__tag_key__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tag_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_datasets_v1_datasets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    get_curation_instructions_v1_datasets__datasetName__curation_instructions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                datasetName: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetCurationInstructions"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_curation_instructions_v1_datasets__datasetName__curation_instructions_put: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
            };
            path: {
                datasetName: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CurationInstructionsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetCurationInstructions"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_dataset_v1_datasets__datasetName__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                datasetName: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_v1_search_get: {
        parameters: {
            query?: {
                /** @description Search query string */
                q?: string | null;
                /** @description Max results (1-50) */
                top?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
