/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         *  Healthz
         * @description Health check endpoint for ACA liveness/readiness probes.
         */
        get: operations["_healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Frontend Config
         * @description Get frontend runtime configuration.
         *
         *     This endpoint exposes backend configuration to the frontend,
         *     allowing runtime configuration without rebuilding the frontend.
         *
         *     Returns:
         *         FrontendConfig: Configuration values for frontend validation behavior
         */
        get: operations["get_frontend_config_v1_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ground-truths/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Stats */
        get: operations["get_stats_v1_ground_truths_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ground-truths": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List All Ground Truths */
        get: operations["list_all_ground_truths_v1_ground_truths_get"];
        put?: never;
        /**
         * Import Bulk
         * @description Bulk import ground truth items.
         *
         *     Behavior:
         *     - ID field: Each item may include 'id' (alias 'uuid'); missing/blank values are generated server-side using
         *       randomname to produce a two-word, hyphenated string (e.g., 'sleek-voxel').
         *     - Order preservation: Response `uuids` mirrors request order for easy correlation.
         *     - Duplicate handling: Existing items are not overwritten; per-item errors are returned in `errors`.
         *     - Optional approval: `approve=true` marks all items approved and sets review metadata.
         */
        post: operations["import_bulk_v1_ground_truths_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ground-truths/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Snapshot
         * @description Return approved items as a downloadable JSON attachment.
         *
         *     Response headers include Content-Disposition so browsers download the file.
         */
        get: operations["download_snapshot_v1_ground_truths_snapshot_get"];
        put?: never;
        /** Snapshot */
        post: operations["snapshot_v1_ground_truths_snapshot_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ground-truths/{datasetName}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Ground Truths */
        get: operations["list_ground_truths_v1_ground_truths__datasetName__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ground-truths/{datasetName}/{bucket}/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ground Truth */
        get: operations["get_ground_truth_v1_ground_truths__datasetName___bucket___item_id__get"];
        /** Update Ground Truth */
        put: operations["update_ground_truth_v1_ground_truths__datasetName___bucket___item_id__put"];
        post?: never;
        /**
         * Delete Item
         * @description Soft-delete a ground truth item.
         */
        delete: operations["delete_item_v1_ground_truths__datasetName___bucket___item_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ground-truths/recompute-tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Recompute Computed Tags
         * @description Recompute computed tags for all matching ground truth items.
         *
         *     This endpoint recalculates the `computedTags` field for all items matching
         *     the optional filter criteria. Use this when:
         *     - A new computed tag plugin has been added
         *     - An existing plugin's logic has been modified
         *     - Data needs to be reprocessed after a bug fix
         *
         *     The operation is idempotent - running it multiple times with the same
         *     data produces the same result.
         *
         *     **Important**: By default, `dry_run=true` for safety. Set `dry_run=false`
         *     to actually persist changes.
         */
        post: operations["recompute_computed_tags_v1_ground_truths_recompute_tags_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/assignments/self-serve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Self Serve Assignments */
        post: operations["self_serve_assignments_v1_assignments_self_serve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/assignments/my": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List My Assignments */
        get: operations["list_my_assignments_v1_assignments_my_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/assignments/{dataset}/{bucket}/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Item */
        put: operations["update_item_v1_assignments__dataset___bucket___item_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/assignments/{dataset}/{bucket}/{item_id}/assign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Assign Item
         * @description Assign a specific ground truth item to the current user.
         *
         *     This endpoint:
         *     - Assigns the item to the current user
         *     - Sets the item status to draft (even if previously approved/deleted/skipped)
         *     - Creates an assignment document in the assignments container
         *     - Returns the updated ground truth item
         */
        post: operations["assign_item_v1_assignments__dataset___bucket___item_id__assign_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/assignments/{dataset}/{bucket}/{item_id}/duplicate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Duplicate Assignment Item
         * @description Duplicate an existing item as a draft rephrase, assign to caller, and return the new item.
         */
        post: operations["duplicate_assignment_item_v1_assignments__dataset___bucket___item_id__duplicate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/schemas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Schemas
         * @description List available component schema names from the OpenAPI document.
         *
         *     Compatibility behavior:
         *     - Returns a list where the first segment contains objects with `name` and `title`
         *         (for newer clients/tests that expect objects), followed by the plain string names
         *         (to preserve backward-compatibility with older callers/tests).
         */
        get: operations["list_schemas_v1_schemas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/schemas/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Schema
         * @description Return a specific component schema by name from the OpenAPI document.
         */
        get: operations["get_schema_v1_schemas__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tags/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Tags Schema */
        get: operations["get_tags_schema_v1_tags_schema_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Tags */
        get: operations["get_tags_v1_tags_get"];
        put?: never;
        /** Post Tags */
        post: operations["post_tags_v1_tags_post"];
        /** Delete Tags */
        delete: operations["delete_tags_v1_tags_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Datasets */
        get: operations["list_datasets_v1_datasets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/datasets/{datasetName}/curation-instructions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Curation Instructions */
        get: operations["get_curation_instructions_v1_datasets__datasetName__curation_instructions_get"];
        /** Put Curation Instructions */
        put: operations["put_curation_instructions_v1_datasets__datasetName__curation_instructions_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/datasets/{datasetName}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Dataset
         * @description Hard-delete a dataset.
         */
        delete: operations["delete_dataset_v1_datasets__datasetName__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_v1_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat */
        post: operations["chat_v1_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddTagsRequest */
        AddTagsRequest: {
            /** Tags */
            tags: string[];
        };
        /**
         * AssignmentUpdateRequest
         * @description Payload for SME update (save draft / approve / skip / delete).
         *
         *     Using a Pydantic model allows camelCase -> snake_case alias handling. All fields optional; we
         *     only mutate those explicitly provided (tracked via model_fields_set).
         */
        AssignmentUpdateRequest: {
            /** Editedquestion */
            editedQuestion?: string | null;
            /** Answer */
            answer?: string | null;
            /** Comment */
            comment?: string | null;
            /** Status */
            status?: components["schemas"]["GroundTruthStatus"] | string | null;
            /** Refs */
            refs?: components["schemas"]["Reference"][] | null;
            /** Manualtags */
            manualTags?: string[] | null;
            /** Approve */
            approve?: boolean | null;
            /** Etag */
            etag?: string | null;
            /** History */
            history?: {
                [key: string]: unknown;
            }[] | null;
        } & {
            [key: string]: unknown;
        };
        /** ChatReference */
        ChatReference: {
            /** Id */
            id?: string | null;
            /** Title */
            title?: string | null;
            /** Url */
            url?: string | null;
            /** Snippet */
            snippet?: string | null;
            /** Keyparagraph */
            keyParagraph?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** ChatRequest */
        ChatRequest: {
            /** Message */
            message: string;
            /** Context */
            context?: string | null;
        };
        /** ChatResponse */
        ChatResponse: {
            /** Content */
            content: string;
            /** References */
            references?: components["schemas"]["ChatReference"][];
        };
        /** CurationInstructionsUpdate */
        CurationInstructionsUpdate: {
            /** Instructions */
            instructions: string;
            /** Etag */
            _etag?: string | null;
        };
        /**
         * DatasetCurationInstructions
         * @description Dataset-level curation instructions document (schemaVersion v1).
         *
         *     Stored in the same Cosmos container as ground-truth items using MultiHash PK
         *     [/datasetName, /bucket] with bucket fixed to 0 and a stable id pattern
         *     "curation-instructions|{datasetName}".
         */
        DatasetCurationInstructions: {
            /** Id */
            id: string;
            /** Datasetname */
            datasetName: string;
            /**
             * Bucket
             * Format: uuid
             */
            bucket?: string;
            /**
             * Doctype
             * @default curation-instructions
             */
            docType: string;
            /**
             * Schemaversion
             * @default v1
             */
            schemaVersion: string;
            /** Instructions */
            instructions: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt?: string;
            /** Updatedby */
            updatedBy?: string | null;
            /** Etag */
            _etag?: string | null;
        };
        /** DependencyDTO */
        DependencyDTO: {
            /** Group */
            group: string;
            /** Value */
            value: string;
        };
        /**
         * ExpectedBehavior
         * @description Expected behavior tags for history items in ground truth evaluation.
         *
         *     These tags describe what the agent should do at each turn of a conversation:
         *     - tool:search: Agent should perform a search/retrieval operation
         *     - generation:answer: Agent should generate a direct answer
         *     - generation:need-context: Agent should ask for more context
         *     - generation:clarification: Agent should ask for clarification
         *     - generation:out-of-domain: Agent should indicate the query is out of domain
         * @enum {string}
         */
        ExpectedBehavior: "tool:search" | "generation:answer" | "generation:need-context" | "generation:clarification" | "generation:out-of-domain";
        /**
         * FrontendConfig
         * @description Frontend runtime configuration.
         */
        FrontendConfig: {
            /** Requirereferencevisit */
            requireReferenceVisit: boolean;
            /** Requirekeyparagraph */
            requireKeyParagraph: boolean;
            /** Selfservelimit */
            selfServeLimit: number;
            /** Trustedreferencedomains */
            trustedReferenceDomains: string[];
        };
        /**
         * GroundTruthItem
         * @description Canonical Ground Truth item aligned to wire schema (schemaVersion v1).
         *
         *     All fields with camelCase wire names use aliases; we accept both field names and aliases
         *     on input (populate_by_name=True) and always serialize using by_alias.
         */
        "GroundTruthItem-Input": {
            /** Id */
            id: string;
            /** Datasetname */
            datasetName: string;
            /** Bucket */
            bucket?: string | null;
            /** @default draft */
            status: components["schemas"]["GroundTruthStatus"];
            /**
             * Doctype
             * @default ground-truth-item
             */
            docType: string;
            /**
             * Schemaversion
             * @default v2
             */
            schemaVersion: string;
            /** Synthquestion */
            synthQuestion: string;
            /** Editedquestion */
            editedQuestion?: string | null;
            /** Answer */
            answer?: string | null;
            /** Refs */
            refs?: components["schemas"]["Reference"][];
            /** Manualtags */
            manualTags?: string[];
            /** Computedtags */
            computedTags?: string[];
            /** Comment */
            comment?: string | null;
            /** History */
            history?: components["schemas"]["HistoryItem"][] | null;
            /** Contextusedforgeneration */
            contextUsedForGeneration?: string | null;
            /** Contextsource */
            contextSource?: string | null;
            /** Modelusedforgeneration */
            modelUsedForGeneration?: string | null;
            /** Semanticclusternumber */
            semanticClusterNumber?: number | null;
            /** Weight */
            weight?: number | null;
            /** Samplingbucket */
            samplingBucket?: number | null;
            /** Questionlength */
            questionLength?: number | null;
            /** Assignedto */
            assignedTo?: string | null;
            /** Assignedat */
            assignedAt?: string | null;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt?: string;
            /** Updatedby */
            updatedBy?: string | null;
            /** Reviewedat */
            reviewedAt?: string | null;
            /** Etag */
            _etag?: string | null;
            /**
             * Totalreferences
             * @default 0
             */
            totalReferences: number;
        };
        /**
         * GroundTruthItem
         * @description Canonical Ground Truth item aligned to wire schema (schemaVersion v1).
         *
         *     All fields with camelCase wire names use aliases; we accept both field names and aliases
         *     on input (populate_by_name=True) and always serialize using by_alias.
         */
        "GroundTruthItem-Output": {
            /** Id */
            id: string;
            /** Datasetname */
            datasetName: string;
            /** Bucket */
            bucket?: string | null;
            /** @default draft */
            status: components["schemas"]["GroundTruthStatus"];
            /**
             * Doctype
             * @default ground-truth-item
             */
            docType: string;
            /**
             * Schemaversion
             * @default v2
             */
            schemaVersion: string;
            /** Synthquestion */
            synthQuestion: string;
            /** Editedquestion */
            editedQuestion?: string | null;
            /** Answer */
            answer?: string | null;
            /** Refs */
            refs?: components["schemas"]["Reference"][];
            /** Manualtags */
            manualTags?: string[];
            /** Computedtags */
            computedTags?: string[];
            /** Comment */
            comment?: string | null;
            /** History */
            history?: components["schemas"]["HistoryItem"][] | null;
            /** Contextusedforgeneration */
            contextUsedForGeneration?: string | null;
            /** Contextsource */
            contextSource?: string | null;
            /** Modelusedforgeneration */
            modelUsedForGeneration?: string | null;
            /** Semanticclusternumber */
            semanticClusterNumber?: number | null;
            /** Weight */
            weight?: number | null;
            /** Samplingbucket */
            samplingBucket?: number | null;
            /** Questionlength */
            questionLength?: number | null;
            /** Assignedto */
            assignedTo?: string | null;
            /** Assignedat */
            assignedAt?: string | null;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt?: string;
            /** Updatedby */
            updatedBy?: string | null;
            /** Reviewedat */
            reviewedAt?: string | null;
            /** Etag */
            _etag?: string | null;
            /**
             * Totalreferences
             * @default 0
             */
            totalReferences: number;
            /**
             * Tags
             * @description Merged view of manualTags and computedTags for API responses.
             *
             *     Returns the union of manual and computed tags, sorted for consistency.
             */
            readonly tags: string[];
        };
        /** GroundTruthListResponse */
        GroundTruthListResponse: {
            /** Items */
            items: components["schemas"]["GroundTruthItem-Output"][];
            pagination: components["schemas"]["PaginationMetadata"];
        };
        /**
         * GroundTruthStatus
         * @enum {string}
         */
        GroundTruthStatus: "draft" | "approved" | "deleted" | "skipped";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HistoryItem
         * @description Represents a single item in the multi-turn history.
         */
        HistoryItem: {
            role: components["schemas"]["HistoryItemRole"];
            /** Msg */
            msg: string;
            /** Refs */
            refs?: components["schemas"]["Reference"][] | null;
            /**
             * Expectedbehavior
             * @description Expected behavior(s) for this turn in the conversation (e.g., tool:search, generation:answer)
             */
            expectedBehavior?: components["schemas"]["ExpectedBehavior"][] | null;
        };
        /**
         * HistoryItemRole
         * @enum {string}
         */
        HistoryItemRole: "user" | "assistant";
        /** ImportBulkResponse */
        ImportBulkResponse: {
            /**
             * Imported
             * @description Number of items successfully imported.
             */
            imported: number;
            /**
             * Errors
             * @description List of error messages for items that failed to import.
             */
            errors: string[];
            /**
             * Uuids
             * @description The item IDs in the same order as the request payload. Clients may send either 'id' or 'uuid' in each item; when missing or blank, the server generates a two-word, hyphenated string ID (e.g., 'sleek-voxel') via randomname.
             */
            uuids?: string[];
        };
        /**
         * PaginationMetadata
         * @description Pagination metadata for list responses.
         */
        PaginationMetadata: {
            /**
             * Page
             * @description Current page number (1-indexed)
             */
            page: number;
            /**
             * Limit
             * @description Items per page
             */
            limit: number;
            /**
             * Total
             * @description Total number of items matching filters
             */
            total: number;
            /**
             * Totalpages
             * @description Total number of pages
             */
            totalPages: number;
            /**
             * Hasnext
             * @description Whether there is a next page
             */
            hasNext: boolean;
            /**
             * Hasprev
             * @description Whether there is a previous page
             */
            hasPrev: boolean;
        };
        /**
         * RecomputeTagsResponse
         * @description Response for bulk computed tag recomputation.
         */
        RecomputeTagsResponse: {
            /**
             * Total
             * @description Total items matching the filter criteria.
             */
            total: number;
            /**
             * Processed
             * @description Number of items successfully processed.
             */
            processed: number;
            /**
             * Updated
             * @description Number of items with changed computed tags.
             */
            updated: number;
            /**
             * Skipped
             * @description Number of items with unchanged computed tags.
             */
            skipped: number;
            /**
             * Errors
             * @description Error messages for failed items.
             */
            errors?: string[];
            /**
             * Dry Run
             * @description Whether this was a dry run (no changes persisted).
             */
            dry_run: boolean;
            /**
             * Duration Ms
             * @description Operation duration in milliseconds.
             */
            duration_ms: number;
        };
        /**
         * Reference
         * @description Wire reference object.
         *
         *     { url, title, content, keyExcerpt, type, bonus, messageIndex }
         */
        Reference: {
            /**
             * Url
             * @description Reference URL (required, non-empty)
             */
            url: string;
            /**
             * Title
             * @description Human-readable title for the reference
             */
            title?: string | null;
            /** Content */
            content?: string | null;
            /** Keyexcerpt */
            keyExcerpt?: string | null;
            /** Type */
            type?: string | null;
            /**
             * Bonus
             * @default false
             */
            bonus: boolean;
            /** Messageindex */
            messageIndex?: number | null;
        };
        /** RemoveTagsRequest */
        RemoveTagsRequest: {
            /** Tags */
            tags: string[];
        };
        /** SelfServeResponse */
        SelfServeResponse: {
            /** Assigned */
            assigned: components["schemas"]["GroundTruthItem-Output"][];
            /** Requested */
            requested: number;
            /** Assignedcount */
            assignedCount: number;
        };
        /**
         * SortField
         * @enum {string}
         */
        SortField: "reviewedAt" | "updatedAt" | "id" | "hasAnswer" | "totalReferences";
        /**
         * SortOrder
         * @enum {string}
         */
        SortOrder: "asc" | "desc";
        /** TagGroupDTO */
        TagGroupDTO: {
            /** Name */
            name: string;
            /** Values */
            values: string[];
            /** Exclusive */
            exclusive: boolean;
            /** Depends On */
            depends_on?: components["schemas"]["DependencyDTO"][];
        };
        /** TagListResponse */
        TagListResponse: {
            /** Tags */
            tags: string[];
            /** Computedtags */
            computedTags?: string[];
        };
        /** TagSchemaResponse */
        TagSchemaResponse: {
            /**
             * Version
             * @default v1
             */
            version: string;
            /** Groups */
            groups: components["schemas"]["TagGroupDTO"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    _healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_frontend_config_v1_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrontendConfig"];
                };
            };
        };
    };
    get_stats_v1_ground_truths_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_all_ground_truths_v1_ground_truths_get: {
        parameters: {
            query?: {
                status?: string | null;
                dataset?: string | null;
                tags?: string | null;
                /** @description Search for items by ID (case-sensitive partial match) */
                itemId?: string | null;
                /** @description Search for items by reference URL (case-sensitive partial match) */
                refUrl?: string | null;
                sortBy?: components["schemas"]["SortField"];
                sortOrder?: components["schemas"]["SortOrder"];
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroundTruthListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_bulk_v1_ground_truths_post: {
        parameters: {
            query?: {
                buckets?: number | null;
                /** @description If true, mark all imported items as approved and set review metadata. */
                approve?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GroundTruthItem-Input"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportBulkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_snapshot_v1_ground_truths_snapshot_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    snapshot_v1_ground_truths_snapshot_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_ground_truths_v1_ground_truths__datasetName__get: {
        parameters: {
            query?: {
                status?: components["schemas"]["GroundTruthStatus"] | null;
            };
            header?: never;
            path: {
                datasetName: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroundTruthItem-Output"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ground_truth_v1_ground_truths__datasetName___bucket___item_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                datasetName: string;
                bucket: string;
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroundTruthItem-Output"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_ground_truth_v1_ground_truths__datasetName___bucket___item_id__put: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
            };
            path: {
                datasetName: string;
                bucket: string;
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroundTruthItem-Output"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_item_v1_ground_truths__datasetName___bucket___item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                datasetName: string;
                bucket: string;
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recompute_computed_tags_v1_ground_truths_recompute_tags_post: {
        parameters: {
            query?: {
                /** @description Filter to items in a specific dataset. If not provided, processes all datasets. */
                dataset?: string | null;
                /** @description Filter to items with a specific status (draft, approved, etc.). */
                status?: components["schemas"]["GroundTruthStatus"] | null;
                /** @description If true, preview changes without persisting. Defaults to true for safety. */
                dry_run?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecomputeTagsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    self_serve_assignments_v1_assignments_self_serve_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SelfServeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_my_assignments_v1_assignments_my_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroundTruthItem-Output"][];
                };
            };
        };
    };
    update_item_v1_assignments__dataset___bucket___item_id__put: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
            };
            path: {
                dataset: string;
                bucket: string;
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignmentUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroundTruthItem-Output"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assign_item_v1_assignments__dataset___bucket___item_id__assign_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset: string;
                bucket: string;
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroundTruthItem-Output"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    duplicate_assignment_item_v1_assignments__dataset___bucket___item_id__duplicate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset: string;
                bucket: string;
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroundTruthItem-Output"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_schemas_v1_schemas_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": ({
                        [key: string]: string;
                    } | string)[];
                };
            };
        };
    };
    get_schema_v1_schemas__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tags_schema_v1_tags_schema_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagSchemaResponse"];
                };
            };
        };
    };
    get_tags_v1_tags_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagListResponse"];
                };
            };
        };
    };
    post_tags_v1_tags_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddTagsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_tags_v1_tags_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RemoveTagsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_datasets_v1_datasets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    get_curation_instructions_v1_datasets__datasetName__curation_instructions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                datasetName: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetCurationInstructions"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_curation_instructions_v1_datasets__datasetName__curation_instructions_put: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
            };
            path: {
                datasetName: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CurationInstructionsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetCurationInstructions"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_dataset_v1_datasets__datasetName__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                datasetName: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_v1_search_get: {
        parameters: {
            query?: {
                /** @description Search query string */
                q?: string | null;
                /** @description Max results (1-50) */
                top?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_v1_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
